config/routes.rb
OnlineTutor::Application.routes.draw do

  devise_for :accounts, :controllers => { registrations: "registrations", omniauth_callbacks: "accounts/omniauth_callbacks" }

  resources :blog, only: [:index, :show]
  
  resources :comments, only: [:create, :index]

  resources :votes, only: [:create]

  get "step1" => "settings#step_one", as: :step_one
  post "set_role" => "settings#set_role", as: :set_role
  get "step2" => "settings#step_two", as: :step_two
  post "save_profile" => "settings#save_profile", as: :save_profile

  namespace :wiki do 
    resources(:attachments) { as_routes }
  end

  root to: "welcome#index"

  namespace :admin do

    resources(:sub_item_in_welcomes) { as_routes }
    resources(:blog_posts) { as_routes }

  end

end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController

	# => only teacher and student can set profile
	before_filter :has_permission_to_set_profile?, only: [:step_two]

	# => step_one is impemented in view

  # => first step in registration: TODO maybe better user can change it after
  def set_role
  	role = params[:role]
  	if Account::POSSIBLE_ROLES.include? role
  		current_account.role = role
  		current_account.save!
  		redirect_to :step_two
  	else
  		flash[:alert] = "There is no role: #{role} in list"
  		render :step_one
  	end
  end

  # => set account profile and depends of role 
  def step_two
  end

  def save_profile
  end

  protected

  # => if user is not teacher or student redirect to main page
  def has_permission_to_set_profile?
    redirect_to :root if !(%{ teacher student }.include? current_account.role)
  end


end

app/views/settings/_set_profile_teacher.html.erb
<div><%= f.label :experience %>(Years)<br />
  <%= f.text_field :experience, class: "form-control" %></div>


<%= f.label :price %><br />
<div class="input-group">
  <span class="input-group-addon">$</span>
  <%= f.text_field :price, class: "form-control", style: "width: 36.5%;" %>
</div>

<div class="set-tags">
	<label for="save_profile_price">Your skills</label>
	<div class="side-by-side clearfix">
       	<div>
	       	<%= select_tag "save_profile[tags]", options_from_collection_for_select(Tag.all, "id", "name"), class: "chosen-select form-control", placeholder: "Choose tags", multiple: true %>
       	</div>
    </div>
</div>

app/views/settings/step_one.html.erb
<div class="choose-how-are">
	<%= link_to "I am a teacher", set_role_path( role: "teacher"), class: "btn btn-primary btn-lg btn-block", method: :post %>
	<%= link_to "I am a student", set_role_path( role: "student"), class: "btn btn-info btn-lg btn-block" %>
</div>

app/views/settings/step_two.html.erb
<script src="https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false&libraries=places"></script>

  <div class="location">
    <h3 class="panel-title">
      Where are you from?
        </h3>
      </div>
    <input id="pac-input" class="controls" type="text"
        placeholder="Enter a location">
    <div id="type-selector" class="controls">
      <input type="radio" name="type" id="changetype-all" checked="checked">
      <label for="changetype-all">All</label>

      <input type="radio" name="type" id="changetype-establishment">
      <label for="changetype-establishment">Establishments</label>

      <input type="radio" name="type" id="changetype-geocode">
      <label for="changetype-geocode">Geocodes</label>
    </div>
    <div id="map-canvas"></div>
<div class="panel panel-primary">
      <div class="panel-heading">
        <h3 class="panel-title">
          Set Your Profile
        </h3>
      </div>
      <div class="panel-body">
<%= form_for(:save_profile, html: { class: "sign-form" }) do |f| %>
  <% if flash[:alert] %>
    <div class="alert alert-danger">
       <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= flash[:alert] %>
    </div>
  <% end %>
  <div><%= f.label :first_name %><br />
  <%= f.text_field :first_name, autofocus: true, class: "form-control" %></div>

  <div><%= f.label :last_name %><br />
    <%= f.text_field :last_name, class: "form-control" %></div>

  <div><%= f.label :sex %><br />
    <%= f.select :sex, ['Male', 'Female'], {}, class: "form-control" %></div>

  <div><%= f.label :age %><br />
    <%= f.text_field :age, class: "form-control" %></div>

  <div><%= f.label :phone_number %><br />
    <div class="input-group">
      <span class="input-group-addon">+</span>
      <%= f.text_field :phone_number, class: "form-control", style: "width: 36.5%" %>
    </div>
  </div>

  <%= f.hidden_field :longitude %>
  <%= f.hidden_field :width %>

  <div><%= f.label :skype %><br />
    <%= f.text_field :skype, class: "form-control" %></div>


  <%= render "set_profile_#{current_account.role}" , f: f %>


<div class="set-tags">
    <div><%= f.label :description, "About You" %><br />
    <%= f.text_area :description, class: "form-control", style: "width: 100%;" %></div>  
</div>
</div>

  <div><%= f.submit "Save", class: "btn btn-primary" %></div>


<% end %>

      </div>
    </div>


































  <script type="text/javascript">
    var config = {
      '.chosen-select'           : {},
      '.chosen-select-deselect'  : {allow_single_deselect:true},
      '.chosen-select-no-single' : {disable_search_threshold:10},
      '.chosen-select-no-results': {no_results_text:'Oops, nothing found!'},
      '.chosen-select-width'     : {width:"95%"}
    }
    for (var selector in config) {
      $(selector).chosen(config[selector]);
    }
  </script>