config/routes.rb
OnlineTutor::Application.routes.draw do

  devise_for :accounts, :controllers => { registrations: "registrations", omniauth_callbacks: "accounts/omniauth_callbacks" }

  resources :blog, only: [:index, :show]
  
  resources :comments, only: [:create, :index]

  resources :votes, only: [:create]

  get "step1" => "settings#step_one", as: :step_one
  post "set_role" => "settings#set_role", as: :set_role
  get "step2" => "settings#step_two", as: :step_two
  post "save_profile" => "settings#save_profile", as: :save_profile

  namespace :wiki do 
    resources(:attachments) { as_routes }
  end

  root to: "welcome#index"

  namespace :admin do

    resources(:sub_item_in_welcomes) { as_routes }
    resources(:blog_posts) { as_routes }

  end

end

app/controllers/blog_controller.rb
class BlogController < ApplicationController

  # => be carefull where skip authenticate
  skip_before_filter :authenticate_account!, only: [:index, :show]

  def index
    @posts = BlogPost.paginate(page: params[:page], per_page: PER_PAGE, include: :comments)
  end

  def show
    @post = BlogPost.find_by_title(params[:id])
    #@post_comments = @post.comments.paginate(page: params[:page], per_page: PER_PAGE, include: :account)

    # => is account liked this post
    @is_account_liked_it = false
    if current_account
      @is_account_liked_it = current_account.voted_for?(@post)
    end
  end

  # => like or dislike post
  # => if request is not ajax return
  def set_vote

    # => render text if request is not ajax
    render text: "" if !request.is_xhr?

    @post = BlogPost.find_by_id(params[:id])

    @is_set_vote = false
    if ["like", "bad"].include?(params[:vote])
      
      # => check if account liked it?
      if !current_account.voted_for?(@post)
        @post.vote_by(voter: current_account, vote: 'like')
        @is_set_vote = true
      end
    end

    render :js
  end
end

app/helpers/blog_helper.rb
module BlogHelper
end

app/views/blog/_blog_post.html.haml
.blog_post
  .image-div
    = image_tag post.avatar.url(:thumb), class: "avatar"
  
  .description
    %h2.title
      = post.title
    
    .content
      = post.description
    .created-at
      Time: 
      = post.created_at.strftime("%k:%m %d:%M%Y")

    = render 'votes/show', namespace_object: post
    .comments
      Comments:
      = post.comments.size
    = link_to "View post", blog_path(post.title), class: "btn btn-success"

app/views/blog/index.html.haml
- @posts.each do | post |
  = render 'blog_post', post: post
.paginator
  = will_paginate @posts, class: "pagination", renderer: BootstrapPagination::Rails, page_links: false

app/views/blog/show.html.haml
.blog_post
  
  %h2.title
    = @post.title
  
  = image_tag @post.avatar.url(:original), class: "avatar"

  .content
    = @post.description

  = render 'votes/show', namespace_object: @post

  = render 'comments/comments', namespace_object: @post, comments: @post_comments