config/routes.rb
OnlineTutor::Application.routes.draw do

  devise_for :accounts, :controllers => { registrations: "registrations", omniauth_callbacks: "accounts/omniauth_callbacks" }

  resources :blog, only: [:index, :show]
  
  resources :comments, only: [:create, :index]

  resources :votes, only: [:create]

  get "step1" => "settings#step_one", as: :step_one
  post "set_role" => "settings#set_role", as: :set_role
  get "step2" => "settings#step_two", as: :step_two
  post "save_profile" => "settings#save_profile", as: :save_profile

  namespace :wiki do 
    resources(:attachments) { as_routes }
  end

  root to: "welcome#index"

  namespace :admin do

    resources(:sub_item_in_welcomes) { as_routes }
    resources(:blog_posts) { as_routes }

  end

end

app/controllers/votes_controller.rb
class VotesController < ApplicationController

  layout false

  before_filter :get_params_for_create_vote, only: [:create]

  # => if request is not ajax return ""
  before_filter :is_ajax_request?

  def create
    if ["like", "bad"].include?(@vote_params[:vote])
      
      # => check if account liked it?
      if !current_account.voted_for?(@namespace_object)
        @namespace_object.vote_by(voter: current_account, vote: @vote_params[:vote])
      end
    end
  end

  def get_params_for_create_vote

  	@vote_params = vote_params

  	if !@vote_params[:namespace_object_id] || !@vote_params[:namespace_object_class]
      render text: "" and return
    end

    @namespace_object = init_namespace_object(@vote_params[:namespace_object_class], @vote_params[:namespace_object_id])
  end

  def vote_params
    params.require(:vote).permit(:namespace_object_class, :namespace_object_id, :vote)
  end

  private 

  def is_ajax_request?
    render text: "" if !request.xhr?
  end

  def init_namespace_object(class_name, id)
    begin
      return Object.const_get(class_name).find(id)
    rescue
      render text: "" and return
    end
  end
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/votes/_links.html.haml
- if current_account && !current_account.voted_for?(namespace_object)
    = link_to "Like", votes_path( vote: { namespace_object_class: namespace_object.class, namespace_object_id: namespace_object.id, vote: "like" }), method: :post, remote: true
    = link_to "Dislike", votes_path( vote: { namespace_object_class: namespace_object.class, namespace_object_id: namespace_object.id, vote: "bad" }), method: :post, remote: true

app/views/votes/_show.html.haml
.likes{ id: "likes_" + dom_id(namespace_object) }
  = render 'votes/vote', namespace_object: namespace_object
  = render 'votes/links' , namespace_object: namespace_object

app/views/votes/_vote.html.haml
Liked:
= namespace_object.get_likes.size
Disliked:
= namespace_object.get_dislikes.size

app/views/votes/create.js.haml
$('#likes_#{dom_id(@namespace_object)}').html("#{ escape_javascript( render 'votes/vote', namespace_object: @namespace_object)}");

= add_gritter("Vote has been created!", title: "Thanks!")