config/routes.rb
OnlineTutor::Application.routes.draw do

  devise_for :accounts, :controllers => { registrations: "registrations", omniauth_callbacks: "accounts/omniauth_callbacks" }

  resources :blog, only: [:index, :show]
  
  resources :comments, only: [:create, :index]

  resources :votes, only: [:create]

  get "step1" => "settings#step_one", as: :step_one
  post "set_role" => "settings#set_role", as: :set_role
  get "step2" => "settings#step_two", as: :step_two
  post "save_profile" => "settings#save_profile", as: :save_profile

  namespace :wiki do 
    resources(:attachments) { as_routes }
  end

  root to: "welcome#index"

  namespace :admin do

    resources(:sub_item_in_welcomes) { as_routes }
    resources(:blog_posts) { as_routes }

  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
  	<title>OnlineTutor</title>
  	<%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  	<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  	<%= csrf_meta_tags %>
	</head>
	<body>
		
		<nav class="navbar navbar-default" role="navigation">
  	
    		<div class="navbar-header">
			      
			    <a class="navbar-brand" href="#" class="logo navbar-left">Logo</a>
			    
			  </div>	
			  
  			<div class="container-fluid">
    

			    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
			      
			      <ul class="nav navbar-nav">
			        <li><a href="#">Registration</a></li>
			        <li class="active"><a href="#">Blog</a></li>
			        <li><a href="#">How to use?</a></li>
			      </ul>

			      <ul class="nav navbar-nav navbar-right">
					<% if account_signed_in? %>
					<% else %> 
	        			<li>
	        				<%= link_to "Sign in",  new_account_session_path %>
	        			</li>
					<% end %>       
        		</ul>	
      
    			</div>

  		</div>

		</nav>
















	    <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>
<%= yield %>















































<div id="footer" class="well">
	2014 - RubyDevelopment
</div> 






</body>
</html>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title OnlineTutor
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true

    = stylesheet_link_tag params[:controller].gsub("/", "_")
    = csrf_meta_tags
  %body
    %nav.navbar.navbar-default{role: "navigation"}
      .navbar-header
        %a.navbar-brand{href: "#"} Logo
      .container-fluid
        #bs-example-navbar-collapse-1.collapse.navbar-collapse
          %ul.nav.navbar-nav
            %li
              %a{href: "#"} Registration
            %li.active
              %a{href: "#"} Blog
            %li
              %a{href: "#"} How to use?
          %ul.nav.navbar-nav.navbar-right
            - if account_signed_in?
            - else
              %li
                = link_to "Sign in",  new_account_session_path
    %p.notice= notice
    %p.alert= alert
    = yield